UserManage/urls.py
from django.urls import include, path
from . import views
app_name = "user_page"

urlpatterns = [
    path("", views.user_page, name='user_page'),
    path("edit/",views.user_edit, name='user_edit'),
    path("post/",views.user_post, name='user_post'),
    path("comment/",views.user_comment, name='user_comment'),
    path("reply/",views.user_reply, name='user_reply'),
    path("favpost/",views.fav_post, name='fav_post'),
]

forum/urls.py
# urls.py

from django.conf import settings
from django.conf.urls import include
from django.urls import path
from .views import home, post_list, new_post, delete_post, edit_post, post_detail, collect_post, remove_collect, collected_posts, new_comment, delete_comment, new_reply, delete_reply

urlpatterns = [

    path('home/', home, name='home'),
    path('PostList/', post_list, name='post_list'),
    path('NewPost/', new_post, name='new_post'),
    path('delete/<int:post_id>/', delete_post, name='delete_post'),
    path('EditPost/<int:post_id>/', edit_post, name='edit_post'),
    path('post/<int:post_id>/', post_detail, name='post_detail'),
    path('post/<int:post_id>/collect/', collect_post, name='collect_post'),
    path('post/<int:post_id>/remove-collect/', remove_collect, name='remove_collect'),
    path('PostList/collected_posts/', collected_posts, name='collected_posts'),
    path('post/<int:post_id>/comment/', new_comment, name='new_comment'),
    path('comment/delete/<int:comment_id>/', delete_comment, name='delete_comment'),
    path('post/<int:post_id>/comment/<int:comment_id>/reply/', new_reply, name='new_reply'),
    path('reply/delete/<int:reply_id>/', delete_reply, name='delete_reply'),
]



web_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from UserManage import views
from web_project import settings

urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include("forum.urls")),
    path('forum/', include('forum.urls')),
    path('login/',views.my_login, name='login'),
    path('register/',views.register,name="register"),
    path('alterpw/',views.alter_pw),
    path('forgetpw/',views.forget_pw),
    path('resetpw/',views.reset_pw),
    path('image/code/',views.img_code),
    path('active',views.account_activate),
    path('reset',views.password_reset),
    path('logout/', views.log_out, name='logout'),
    path('userpage/',include("UserManage.urls")),
]

UserManage/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=64)

UserManage/views.py
import uuid
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect , HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.template.response import TemplateResponse

from UserManage.utils.imgcode import check_code
from io import BytesIO
from django import forms
from UserManage.utils import validators,randomstr
from django.core.mail import send_mail
from forum.models import Post,Subject,Collect,Comment,Reply


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'placeholder':'请输入用户名'}),

    )
    password = forms.CharField(
        max_length=120,
        required=True,
        widget=forms.PasswordInput(attrs={ 'placeholder': '请输入密码'})
    )
    imgcode = forms.CharField(
        max_length=5,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': '请输入验证码','style':"width: 125px"})
    )


class RegisterForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'placeholder':'请输入用户名'}),
        validators=[validators.validate_username]
    )
    email = forms.EmailField(
        max_length=254,
        required=True,
        widget=forms.EmailInput(attrs={'placeholder': '请输入邮箱'})
    )
    password = forms.CharField(
        min_length=8,
        max_length=120,
        required=True,
        widget=forms.PasswordInput(attrs={ 'placeholder': '请输入密码'}),
        validators = [validators.validate_password]
    )
    password2 = forms.CharField(
        max_length=120,
        required=True,
        widget=forms.PasswordInput(attrs={'placeholder': '请再次输入您设置的密码'})
    )
    imgcode = forms.CharField(
        max_length=5,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': '请输入验证码', 'style': "width: 125px"})
    )

class ForgetForm(forms.Form):
    email = forms.EmailField(
        max_length=254,
        required=True,
        widget=forms.EmailInput(attrs={'placeholder': '请输入您在注册时使用的邮箱'})
    )
    imgcode = forms.CharField(
        max_length=5,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': '请输入验证码', 'style': "width: 125px"})
    )

class AlterForm(forms.Form):
    email = forms.EmailField(
        max_length=254,
        required=True,
        widget=forms.EmailInput(attrs={'placeholder': '请输入您在注册时使用的邮箱'})
    )
    imgcode = forms.CharField(
        max_length=5,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': '请输入验证码', 'style': "width: 125px"})
    )

class ResetForm(forms.Form):
    password = forms.CharField(
        min_length=8,
        max_length=120,
        required=True,
        widget=forms.PasswordInput(attrs={ 'placeholder': '请输入密码'}),
        validators = [validators.validate_password]
    )
    password2 = forms.CharField(
        max_length=120,
        required=True,
        widget=forms.PasswordInput(attrs={'placeholder': '请再次输入您设置的密码'})
    )

class EditForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'placeholder':'请输入用户名',"class":"form-control"}),
        validators=[validators.validate_username]
    )
    first_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={ 'placeholder': '请输入名字',"class":"form-control"}),
        validators = [validators.validate_name]
    )
    last_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': '请输入姓氏',"class":"form-control"}),
        validators = [validators.validate_name]
    )




def my_login(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        remember = request.POST.get('rememberpw')
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user_code = form.cleaned_data.pop('imgcode').lower()
            real_code = request.session.get('imgcode',"").lower()
            if real_code == "":
                form.add_error("imgcode", "验证码已过期!")
                return TemplateResponse(request, 'login.html', {'form': form})
            elif real_code != user_code:
                form.add_error("imgcode", "验证码错误!")
                return TemplateResponse(request, 'login.html', {'form': form})
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                if remember != 'true':
                    request.session.set_expiry(0)
                else:
                    request.session.set_expiry(None)
                return redirect('post_list')  
            else:
                form.add_error("imgcode","用户名或密码错误!")
                return TemplateResponse(request, 'login.html', {'form': form})
        else:
            return TemplateResponse(request, 'login.html', {'form': form})
    return TemplateResponse(request, "login.html", {'form': LoginForm()})



def register(request):
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            user_code = form.cleaned_data.pop('imgcode').lower()
            real_code = request.session.get('imgcode', "").lower()
            if real_code == "":
                form.add_error("imgcode", "验证码已过期!")
                return render(request, 'register.html', {'form': form})
            elif real_code != user_code:
                form.add_error("imgcode", "验证码错误!")
                return render(request, 'register.html', {'form': form})
            elif User.objects.filter(username=form.cleaned_data['username']).exists():
                form.add_error("username", "用户名已被注册过！")
                return render(request, 'register.html', {'form': form})
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                form.add_error("email", "邮箱已被注册过！")
                return render(request, 'register.html', {'form': form})
            elif form.cleaned_data['password'] != form.cleaned_data['password2']:
                form.add_error("password2", "两次输入的密码不一致！")
                return render(request, 'register.html', {'form': form})
            else:
                cuser = User.objects.create_user(username=form.cleaned_data['username'], password=form.cleaned_data['password'],email=form.cleaned_data['email'],is_active=False)
                cuser.save()
                # 使用uuid产生一个token
                token = str(uuid.uuid4()).replace('-', '')
                # 使用session存储token
                request.session[token] = form.cleaned_data['username']
                request.session.save()  # 保存session到数据库或缓存
                request.session.set_expiry(60 * 60 * 24)
                username = User.objects.get(email=form.cleaned_data['email']).username
                subject = "信安综合网站账号激活邮件"
                path = f'http://127.0.0.1:8000/active?token={token}'  # 这里记得要改成最终公网地址
                message = f"""
                                                <html>
                                                    <head>
                                                        <style>
                                                            body {{
                                                                font-family: Arial, sans-serif;
                                                                background-color: #f2f2f2;
                                                            }}

                                                            .container {{
                                                                position: relative;
                                                                max-width: 600px;
                                                                margin: 0 auto;
                                                                padding: 20px;
                                                                background-color: #fff;
                                                                border-radius: 5px;
                                                                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
                                                            }}

                                                            h1 {{
                                                                color: #333;
                                                                font-size: 24px;
                                                                margin-bottom: 20px;
                                                            }}

                                                            p {{
                                                                color: #555;
                                                                font-size: 16px;
                                                                line-height: 1.5;
                                                            }}

                                                            a {{
                                                                color: #007bff;
                                                                text-decoration: none;
                                                            }}

                                                            a:hover {{
                                                                text-decoration: underline;
                                                            }}

                                                            p.signature {{
                                                                position: absolute;

UserManage/templates/editpage.html
{% extends 'base.html' %}
{%  load static %}

{% block page_content %}
    <div class="container-fluid">
    <div class="row" style="height: 100vh">

            <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary" >
      <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel" >
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="sidebarMenuLabel">信安综合网站</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
        </div>

        <div class="flex-0 p-3" style="width: 280px;">
            <ul class="list-unstyled ps-0" style="margin-top: 10px">

                <li class="mb-1 mysidebar" >
                    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 mybutton" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="false">个人信息
                    </button>
                            <div class="collapse" id="home-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="/userpage/" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >个人信息</a></li>
          </ul>
        </div>
                </li>
                <br/>
                <li class="mb-1 mysidebar">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 mybutton" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
          收藏夹
        </button>
                                                <div class="collapse" id="dashboard-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'user_page:fav_post' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >收藏的帖子</a></li>
          </ul>
        </div>
      </li>
                <br/>
                <li class="mb-1 mysidebar">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed mybutton" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
          我的发布
        </button>
        <div class="collapse" id="orders-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'user_page:user_post' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >发布的帖子</a></li>
            <li><a href="{% url 'user_page:user_comment' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >发布的评论</a></li>
            <li><a href="{% url 'user_page:user_reply' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >发布的回复</a></li>
          </ul>
        </div>
      </li>
            </ul>
        </div>
      </div>
    </div>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="border-bottom: 1px solid lightgrey">

    <div class="py-5 text-center">
      <h2>个人信息</h2>
    </div>
    <div class="row g-12">
      <div class="col-md-6 col-lg-6 offset-3 ">
        <form class="needs-validation" method="post" novalidate>
            {% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="lastName" class="form-label">姓氏</label>
{#              <input type="text" class="form-control" id="lastName" placeholder="{{ lastname }}" >#}
                {{ form.last_name }}
                <span style="color: red">{{ form.last_name.errors.0 }}</span>
            </div>

            <div class="col-sm-6">
              <label for="firstName" class="form-label">名字</label>
{#              <input type="text" class="form-control" id="firstName" placeholder="{{ firstname }}">#}
                {{ form.first_name }}
                <span style="color: red">{{ form.first_name.errors.0 }}</span>
            </div>

            <div class="col-12">
              <label for="username" class="form-label">用户名</label>
{#                <input type="text" class="form-control" id="username" placeholder="{{ username }}">#}
                  {{ form.username }}
                <span style="color: red">{{ form.username.errors.0 }}</span>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">邮箱</label>
              <input type="email" class="form-control" id="email" placeholder="{{ email }}" disabled>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">加入时间</label>
                <input type="text" class="form-control" id="join_time" placeholder="{{ join_time }}" disabled>
            </div>
              <br/>
            <div class="col-sm-12">
                <button class="w-100 btn btn-primary btn-lg" type="submit" style="margin-top: 20px">保存修改</button>
            </div>
          </div>
        </form>
          <div class="row g-3">
              <div class="col-sm-12">
                <button class="w-100 btn btn-primary btn-lg" style="margin-top: 20px;margin-bottom: 30px" onclick="window.location.href = '{% url 'user_page:user_page' %}'">取消修改</button>
            </div>
          </div>
      </div>
    </div>
    </main>
    </div>
    </div>
{% endblock %}

UserManage/templates/favpost.html
{% extends 'base.html' %}
{%  load static %}

{% block page_content %}
    <div class="container-fluid">
    <div class="row" style="height: 100vh">
    <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
      <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel" >
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="sidebarMenuLabel">信安综合网站</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
        </div>

        <div class="flex-0 p-3" style="width: 280px;">
            <ul class="list-unstyled ps-0" style="margin-top: 10px">

                <li class="mb-1 mysidebar" >
                    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 mybutton" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="false">个人信息
                    </button>
                            <div class="collapse" id="home-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="/userpage/" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >个人信息</a></li>
          </ul>
        </div>
                </li>
                <br/>
                <li class="mb-1 mysidebar">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 mybutton" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
          收藏夹
        </button>
                                                <div class="collapse" id="dashboard-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'user_page:fav_post' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >收藏的帖子</a></li>
          </ul>
        </div>
      </li>
                <br/>
                <li class="mb-1 mysidebar">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed mybutton" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
          我的发布
        </button>
        <div class="collapse" id="orders-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'user_page:user_post' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >发布的帖子</a></li>
            <li><a href="{% url 'user_page:user_comment' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >发布的评论</a></li>
            <li><a href="{% url 'user_page:user_reply' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >发布的回复</a></li>
          </ul>
        </div>
      </li>
            </ul>
        </div>
      </div>
    </div>


    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="border-bottom: 1px solid lightgrey">
<br/>
        <div class="card mb-4">
            <div class="card-header text-center">
                <h3>我收藏的帖子</h3>
            </div>
            <div class="card-body">
                {% if posts %}
                    <ul class="list-group">
                        {% for post in posts %}
                            <a href="{% url 'post_detail' post.id %}" class="list-group-item list-group-item-action d-flex justify-content-between">
                                <span>{{ post.title }}</span>
                                <small class="text-muted">创建于 {{ post.created_at|date:"Y-m-d H:i" }}</small>
                            </a>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>你还没有收藏任何帖子。</p>
                {% endif %}
            </div>
        </div>


    </main>
    </div>
    </div>
    <div class="card shadow">
      <div class="card-footer bg-body-tertiary">
          <h1 class="text-center"><code>THAT'S THE END</code></h1>
      </div>
    </div>
{% endblock %}

UserManage/templates/forgetpw.html
{% extends 'base.html' %}
{%  load static %}

{% block style %}
    <title>忘记密码</title>
    <link rel="stylesheet" href="{% static 'css/loginstyle.css' %}"/>
{% endblock %}


{% block page_content %}
    <div class="box mx-auto">
        <h2>找回密码</h2>
        <form method="post" novalidate>
            {% csrf_token %}
        <div class="input-box">
            <label>邮箱</label>
            {{ form.email }}
            <span class ="wrong">{{ form.email.errors.0 }}</span>
        </div>
        <div class="input-box">
            <label>验证码</label>
            <div>
                {{ form.imgcode }}
            <a href="/forgetpw/"><img id="imgcode" src="/image/code/" alt="验证码"/></a>
            </div>
            <span class ="wrong">{{ form.imgcode.errors.0 }}</span>
        </div>
        <div class="btn-box">
            <div style="margin-top: 20px;">
                <button type="submit" style="width: 250px">下一步</button>
            </div>
        </div>
        </form>
        <div class="btn-box">
            <div><button onclick="window.location.href = '/login/'" style="width: 250px;margin-bottom: 20px">返回登录界面</button></div>
        </div>
    </div>
{% endblock %}

UserManage/templates/login.html
{% extends 'base.html' %}
{%  load static %}

{% block style %}
    <title>登录</title>
    <link rel="stylesheet" href="{% static 'css/loginstyle.css' %}"/>
{% endblock %}


{% block page_content %}
    <div class="box mx-auto">
        <h2>登录</h2>
        <form method="post" action="/login/" novalidate>
            {% csrf_token %}
        <div class="input-box" >
            <label >用户名</label>
            {{ form.username }}
            <span class ="wrong">{{ form.username.errors.0 }}</span>
        </div>
        <div class="input-box" >
            <label>密码</label>
            {{ form.password }}
            <span class ="wrong" >{{ form.password.errors.0 }}</span>
        </div>
        <div class="input-box" style="margin-bottom: 0">
            <label>验证码</label>
            <div>
            {{ form.imgcode }}
            <a href="/login/"><img id="imgcode" src="/image/code/" alt="验证码"/></a>
            </div>
            <span class ="wrong">{{ form.imgcode.errors.0 }}</span>
        </div>
        <div class="btn-box">
            <div>
            <input type="checkbox"  value="true" name="rememberpw"/>
            <label id="remember">记住密码</label>
            </div>
            <div>
                <button style="width: 250px;margin-top: 15px;" id="loginbn" type="submit">登录</button>
            </div>
        </div>
        </form>
        <div class="btn-box">
            <div>
                <button onclick="window.location.href = '/register/'" id="regisbn">注册</button>
                <button onclick="window.location.href = '{{ last_url }}'" id="visitorbn" >以游客身份浏览</button>
            </div>
            <div style="margin-top: 10px;justify-content: flex-end;margin-left: auto;">
                <a href="/forgetpw/" style="width: auto;">忘记密码?</a>
            </div>
            <div>

            </div>
        </div>
        {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
        {% endif %}
    </div>
{% endblock %}

UserManage/templates/userpage.html
{% extends 'base.html' %}
{%  load static %}

{% block page_content %}
    <div class="container-fluid">
    <div class="row" style="height: 100vh">

            <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary" >
      <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel" >
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="sidebarMenuLabel">信安综合网站</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
        </div>

        <div class="flex-0 p-3" style="width: 280px;">
            <ul class="list-unstyled ps-0" style="margin-top: 10px">

                <li class="mb-1 mysidebar" >
                    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 mybutton" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="false">个人信息
                    </button>
                            <div class="collapse" id="home-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="/userpage/" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >个人信息</a></li>
          </ul>
        </div>
                </li>
                <br/>
                <li class="mb-1 mysidebar">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 mybutton" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
          收藏夹
        </button>
        <div class="collapse" id="dashboard-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'user_page:fav_post' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >收藏的帖子</a></li>
          </ul>
        </div>
      </li>
                <br/>
                <li class="mb-1 mysidebar">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed mybutton" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
          我的发布
        </button>
        <div class="collapse" id="orders-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'user_page:user_post' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >发布的帖子</a></li>
            <li><a href="{% url 'user_page:user_comment' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >发布的评论</a></li>
            <li><a href="{% url 'user_page:user_reply' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded" >发布的回复</a></li>
          </ul>
        </div>
      </li>
            </ul>
        </div>
      </div>
    </div>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="border-bottom: 1px solid lightgrey">

    <div class="py-5 text-center">
      <h2>个人信息</h2>
    </div>
    <div class="row g-12">
      <div class="col-md-6 col-lg-6 offset-3 ">
        <form class="needs-validation" novalidate="">
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="lastName" class="form-label">姓氏</label>
              <input type="text" class="form-control" id="lastName" placeholder="{{ lastname }}" value="" required="" disabled>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="firstName" class="form-label">名字</label>
              <input type="text" class="form-control" id="firstName" placeholder="{{ firstname }}" value="" required="" disabled>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="username" class="form-label">用户名</label>
              <div class="input-group has-validation">
                <input type="text" class="form-control" id="username" placeholder="{{ username }}" required="" disabled>
              <div class="invalid-feedback">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">邮箱</label>
              <input type="email" class="form-control" id="email" placeholder="{{ email }}" disabled>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">加入时间</label>
                <input type="text" class="form-control" id="join_time" placeholder="{{ join_time }}" disabled>
            </div>

          </div>
            <br/>
        </form>
          <button class="w-100 btn btn-primary btn-lg" type="submit" style="margin-top: 10px" onclick="window.location.href = '{% url 'user_page:user_edit' %}'">修改基础信息</button>
          <button class="w-100 btn btn-primary btn-lg" style="margin-top: 30px;margin-bottom: 50px" onclick="window.location.href = '/alterpw/'" >更改用户密码</button>
      </div>
    </div>
    </main>
    </div>
    </div>
    <div class="card shadow">
      <div class="card-footer bg-body-tertiary">
          <h1 class="text-center"><code>THAT'S THE END</code></h1>
      </div>
    </div>
{% endblock %}