UserManage/urls.py
from django.urls import include, path
from . import views
app_name = "user_page"

urlpatterns = [
    path("", views.user_page, name='user_page'),
    path("edit/",views.user_edit, name='user_edit'),
    path("post/",views.user_post, name='user_post'),
    path("comment/",views.user_comment, name='user_comment'),
    path("reply/",views.user_reply, name='user_reply'),
    path("favpost/",views.fav_post, name='fav_post'),
]

forum/urls.py
# urls.py

from django.conf import settings
from django.conf.urls import include
from django.urls import path
from .views import home, post_list, new_post, delete_post, edit_post, post_detail, collect_post, remove_collect, collected_posts, new_comment, delete_comment, new_reply, delete_reply

urlpatterns = [

    path('home/', home, name='home'),
    path('PostList/', post_list, name='post_list'),
    path('NewPost/', new_post, name='new_post'),
    path('delete/<int:post_id>/', delete_post, name='delete_post'),
    path('EditPost/<int:post_id>/', edit_post, name='edit_post'),
    path('post/<int:post_id>/', post_detail, name='post_detail'),
    path('post/<int:post_id>/collect/', collect_post, name='collect_post'),
    path('post/<int:post_id>/remove-collect/', remove_collect, name='remove_collect'),
    path('PostList/collected_posts/', collected_posts, name='collected_posts'),
    path('post/<int:post_id>/comment/', new_comment, name='new_comment'),
    path('comment/delete/<int:comment_id>/', delete_comment, name='delete_comment'),
    path('post/<int:post_id>/comment/<int:comment_id>/reply/', new_reply, name='new_reply'),
    path('reply/delete/<int:reply_id>/', delete_reply, name='delete_reply'),
]



web_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from UserManage import views
from web_project import settings

urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include("forum.urls")),
    path('forum/', include('forum.urls')),
    path('login/',views.my_login, name='login'),
    path('register/',views.register,name="register"),
    path('alterpw/',views.alter_pw),
    path('forgetpw/',views.forget_pw),
    path('resetpw/',views.reset_pw),
    path('image/code/',views.img_code),
    path('active',views.account_activate),
    path('reset',views.password_reset),
    path('logout/', views.log_out, name='logout'),
    path('userpage/',include("UserManage.urls")),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Subject(models.Model):
    name = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Collect(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    def __str__(self):
        return self.user

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Reply(models.Model):
    comment = models.ForeignKey(Comment, related_name='replies', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

forum/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post,Subject,Collect,Comment,Reply
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import connection, transaction
from django.core.paginator import Paginator

from django.utils import timezone
#import pytz

def home(request):
    return render(request, 'home.html')

def post_list(request):
    subjects = Subject.objects.all()  
    selected_subject = request.GET.get('subject')  
    collected_filter = request.GET.get('collected', '') 

    if selected_subject:
        posts = Post.objects.filter(subject__name=selected_subject)
    else:
        posts = Post.objects.all()

    if collected_filter == "yes":
        posts = posts.filter(id__in=Collect.objects.filter(user=request.user).values('post_id'))
    if collected_filter == "no":
        posts = Post.objects.all()

    paginator = Paginator(posts, 8)  # 每页显示8个帖子
    page_number = request.GET.get('page')  
    page_obj = paginator.get_page(page_number)  

    return render(request, 'post_list.html', {
        'posts': posts,
        'page_obj': page_obj,
        'subjects': subjects,
        'selected_subject': selected_subject,
        'collected_filter': collected_filter,
    })

@login_required(login_url='/login/')
def new_post(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        subject_name = request.POST.get('subject')
        user = request.user
        print(f"Title: '{title}', Content: '{content}', subject_name: '{subject_name}'")  # 调试输出


        if title and content: 
            subject, created = Subject.objects.get_or_create(name=subject_name)

            post = Post(title=title, content=content, user=user, subject=subject)
            post.save()

            messages.success(request, "帖子已成功发布。")
            return redirect('post_list') 
        else:
            messages.error(request, "标题和内容不能为空。")

    subjects = Subject.objects.all() 
    return render(request, 'new_post.html', {
        'user_id': request.user.id,
        'username': request.user.username,
        'subjects': subjects,
    })

"""""
@login_required(login_url='/login/')
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if post.user != request.user:
        messages.error(request, "你没有权限删除这篇帖子。")
        return redirect('post_list')

    post.delete()
    return redirect('post_list')  
"""""

@login_required(login_url='/login/')
def delete_post(request, post_id):
    current_user_id = request.user.id

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT user_id FROM forum_post
            WHERE id = %s
        """, [post_id])
        row = cursor.fetchone()

    if not row or row[0] != current_user_id:
        messages.error(request, "你没有权限删除这篇帖子。")
        return redirect('post_list')

    with transaction.atomic():
        Collect.objects.filter(post_id=post_id).delete()

        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM forum_post WHERE id = %s", [post_id])

    return redirect('post_list')
"""
@login_required(login_url='/login/')
def edit_post(request, post_id):
    #print("GET data:", request.GET)
    #print("POST data:", request.POST)

    post = get_object_or_404(Post, id=post_id)

    if post.user != request.user:
        messages.error(request, "你没有权限编辑这篇帖子。")
        return redirect('post_list')

    if request.method == 'POST':

        title = request.POST.get("title","").strip()
        content = request.POST.get("content","").strip()
        subject_name = request.POST.get('subject',"").strip()
        print(f"Title: '{title}', Content: '{content}', subject_name: '{subject_name}'")  # 调试输出

        if title and content and subject_name:
            post.title = title
            post.content = content

            subject, created = Subject.objects.get_or_create(name=subject_name)
            post.subject = subject

            post.updated_at = timezone.now()  
            post.save()

            messages.success(request, "帖子已成功更新。")
            return redirect('post_list')  
        else:
            messages.error(request, "主题不能为空")


    subjects = Subject.objects.all()
    return render(request, 'edit_post.html', {
        'post': post,
        'subjects': subjects,
    })
"""
@login_required(login_url='/login/')
def edit_post(request, post_id):
    current_user_id = request.user.id

    post = get_object_or_404(Post, id=post_id)

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT user_id FROM forum_post
            WHERE id = %s
        """, [post_id])
        row = cursor.fetchone()

    if not row or row[0] != current_user_id:
        messages.error(request, "你没有权限编辑这篇帖子。")
        return redirect('post_list')

    if request.method == 'POST':
        title = request.POST.get('title')  
        content = request.POST.get('content')  

        if not title or not content:
            messages.error(request, "标题和内容不能为空。")
            return render(request, 'edit_post.html', {'post': post})

        title = title.strip() if title else ''
        content = content.strip() if content else ''

        with transaction.atomic():
            # 代码中所有与数据库交互的SQL查询都使用了参数化查询，如%s，
            # 将变量绑定到查询参数，而不是直接插入SQL字符串中，可以有效防止SQL注入攻击。
            with connection.cursor() as cursor:
                cursor.execute("""
                    UPDATE forum_post 
                    SET title = %s, content = %s, updated_at = NOW()
                    WHERE id = %s
                """, [title, content, post_id])

            post.title = title
            post.content = content
            post.save()

        messages.success(request, "帖子更新成功！")
        return redirect('post_detail', post_id=post_id)

    return render(request, 'edit_post.html', {'post': post})



def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    is_collected = Collect.objects.filter(user=request.user, post=post).exists() if request.user.is_authenticated else False
    return render(request, 'post_detail.html', {
        'post': post,
        'is_collected': is_collected,
    })

@login_required(login_url='/login/')
def collect_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    collect, created = Collect.objects.get_or_create(user=request.user, post=post)
    if created:
        messages.success(request, '成功收藏该帖子！')
    else:
        messages.info(request, '你已经收藏过这个帖子。')
    return redirect('post_detail', post_id=post_id)

@login_required(login_url='/login/')
def remove_collect(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    collect = Collect.objects.filter(user=request.user, post=post).first()
    if collect:
        collect.delete()
        messages.success(request, '成功移除收藏！')
    return redirect('post_detail', post_id=post_id)

@login_required(login_url='/login/')
def collected_posts(request, post_id):
    collected_posts = Collect.objects.filter(user=request.user).values_list('post', flat=True)
    posts = Post.objects.filter(id__in=collected_posts)
    return render(request, 'collected_posts.html', {'posts'})

@login_required(login_url='/login/')
def new_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        username = request.POST.get('username')
        content = request.POST.get('content')
        print(f"user:,'{username}',content:, '{content}'")

        if content:  
            comment = Comment(content=content, user=request.user, post=post)
            comment.save()
            messages.success(request, "评论已成功发布。")
            return redirect('post_detail', post_id=post_id)  
        else:
            messages.error(request, "请补全评论内容。")

    return render(request, 'new_comment.html', {
        'post': post,
        'post_id': post_id,
    })


@login_required(login_url='/login/')
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if comment.user != request.user:
        messages.error(request, "你没有权限删除这条评论。")
        return redirect('post_list')

    comment.delete()
    messages.success(request, "评论已成功删除。")
    return redirect('post_list') 


@login_required(login_url='/login/')
def new_reply(request, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if request.method == 'POST':
        username = request.POST.get('username')
        content = request.POST.get('content')
        print(f"user:,'{username}',content:, '{content}'")

        if content: 
            reply = Reply(content=content, user=request.user, comment=comment)
            reply.save()
            messages.success(request, "回复已成功发布。")
            return redirect('post_detail', post_id=post_id) 
        else:
            messages.error(request, "请补全回复内容。")

    return render(request, 'new_reply.html', {
        'comment': comment,
    })


@login_required(login_url='/login/')
def delete_reply(request, post_id, reply_id):
    reply = get_object_or_404(Reply, id=reply_id)

    if reply.user != request.user:
        messages.error(request, "你没有权限删除这条回复。")
        return redirect('post_detail', post_id=post_id)

    reply.delete()
    messages.success(request, "回复已成功删除。")
    return redirect('post_detail', post_id=post_id) 

forum/templates/base.html
{% extends 'root.html' %}
{% load static %}
{% load tz %}

{% block title %}论坛{% endblock %}

{% block style %}
<link rel="icon" href="{% static 'images/Spider-Man.ico' %}">
<link rel="stylesheet" href="{% static 'plugins/bootstrap-5.3.3-dist/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/userpage.css' %}">
{% endblock %}

{% block script %}
<script src="{% static 'js/CustomizeSubject.js' %}"></script>
{% if messages %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            {% for message in messages %}
                alert("{{ message|escapejs }}");  // 弹出窗口显示消息
            {% endfor %}
        });
    </script>
{% endif %}
{% endblock %}

{% block content %}

    <div>
        <div class="card shadow">
            <div class="card-header bg-body-tertiary">
                <h1 class="text-center"><code>That's the beginning</code></h1>
            </div>
            <main>
                {% block content_header_inner %}{% endblock %}
            </main>
        </div>

        <!-- 页面内容区域 -->
        <div class="my-5 container">
            {% block page_content %}
            {% endblock %}
        </div>
        <div class="card shadow">
            <main>
                {% block content_footer_inner %}{% endblock %}
            </main>
            <div class="card-footer bg-body-tertiary">
                <h1 class="text-center"><code>THAT'S THE END!</code></h1>
            </div>
        </div>
    </div>

{% endblock %}

forum/templates/edit_post.html

<!-- templates/edit_post.html -->
{% extends 'base.html' %}

{% block page_content %}
<h2  class="fw-bold text-center">编辑帖子</h2>
<form method="POST">
    {% csrf_token %}
    <div class="container p-5 my-5 border">
        <div class="input-group mb-3">
            <span class="fw-bold input-group-text">当前用户： </span>
            <input readonly class="form-control" value="{{ post.user.username }}"></input>
        </div>
        <!-- 在Django模板中，只要不使用safe或mark_safe标签，Django会自动对变量进行HTML转义。
         在这段代码中，{{ post.title }}和{{ post.content }}会被自动转义。 -->
        <div class = "mb-3">
            <label class="fw-bold mb-3">标题:</label>
            <input type="text" name="title" class="form-control" value="{{ post.title }}" required>
        </div>
        <div class = "mb-3">
            <label class="fw-bold mb-3">内容:</label>
            <textarea name="content" class="form-control" required>{{ post.content }}</textarea>
        </div>
        <div class = "mb-3">
            <label  class="fw-bold mb-3" for="subject-select">主题:</label>
            <select class="form-select" name="subject" id="subject-select">
                <option value="">选择主题</option>
                {% for subject in subjects %}
                    <option value="{{ subject.name }}" >{{ subject.name }}</option>
                {% endfor %}
                <option value="自定义">自定义</option>
            </select>
            <input type="text" class="form-control" id="custom-subject" name="subject" placeholder="输入自定义主题" style="display:none;">
        </div>

        <div class = "text-center">
            <button type="submit" class="btn btn-outline-success">更新帖子</button>
        </div>
    </div>
</form>

{% endblock %}

forum/templates/post_detail.html
<!-- templates/post_detail.html -->
{% extends 'base.html' %}

{% block page_content %}
<div>
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-md-8">  <!-- 设置列宽 -->
                <div class="p-5 my-5 border">
                    <h2 class="text-center mb-3"><code class="fw-bold">{{ post.title }}</code></h2>
                    <div class="input-group mb-3">
                        <span class="input-group-text"> &ensp;主&ensp;&ensp;题&ensp; </span>
                        <input readonly class="form-control text-center" value="{{ post.subject }}">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"> &ensp;内&ensp;&ensp;容&ensp; </span>
                        <textarea readonly class="form-control text-center" style="height: 38px;">{{ post.content }}</textarea>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"> &ensp;用&ensp;&ensp;户&ensp; </span>
                        <input readonly class="form-control text-center" value="{{ post.user.username }}">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"> 发帖时间 </span>
                        <input readonly class="form-control text-center" value="{{ post.created_at }}">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"> 最后更新 </span>
                        <input readonly class="form-control text-center" value="{{ post.updated_at }}">
                    </div>
                    <div class="text-center">
                        <form action="{% url 'new_comment' post.id %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-light btn-lg">评论</button>
                        </form>
                        <form action="{% url 'edit_post' post.id %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-warning btn-lg">编辑</button>
                        </form>
                        <form action="{% url 'delete_post' post.id %}" method="POST" style="display:inline;" onsubmit="return confirmDelete();">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger btn-lg">删除</button>
                        </form>
                        <form action="{% if is_collected %}{% url 'remove_collect' post.id %}{% else %}{% url 'collect_post' post.id %}{% endif %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            {% if is_collected %}
                                <button type="submit" class="btn btn-outline-secondary btn-lg">取消收藏</button>
                            {% else %}
                                <button type="submit" class="btn btn-outline-success btn-lg">收藏</button>
                            {% endif %}
                        </form>
                    </div>
                </div>

                <!-- 评论部分 -->
                <div class="container mt-4 mb-4 border">
                    <h2 class="mt-5 mb-5">评论</h2>
                    <table class="table table-bordered mb-5">
                        <tbody>
                        {% for comment in post.comment_set.all %}
                            <tr class="text-center">
                                <td style="width: 35%;">
                                    <textarea readonly class="form-control text-center" style="height: 38px;">{{ comment.content }}</textarea>
                                </td>
                                <td style="width: 35%;">
                                    <span>由&ensp;<code>{{ comment.user.username }}</code></span>
                                    <span>创建于&ensp;<code>{{ comment.created_at }}</code></span>
                                </td>
                                <td style="width: 20%;">
                                    <form action="{% url 'delete_comment' comment.id %}" method="POST" style="display:inline;" onsubmit="return confirmDelete();">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-outline-danger btn-sm">删除</button>
                                    </form>
                                    <form action="{% url 'new_reply' post.id comment.id %}" method="POST" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-outline-secondary btn-sm">回复</button>
                                    </form>
                                </td>
                            </tr>
                            {% for reply in comment.replies.all %}
                                <tr>
                                <td colspan="1" style="width: 35%; text-align: left; padding-left: 50px;">
                                    <textarea readonly class="form-control text-center" style="height: 38px;">{{ reply.content }}</textarea>
                                </td>
                                <td style="width: 35%;">
                                    <span>由&ensp;<code>{{ reply.user.username }}</code></span>
                                    <span>回复于&ensp;<code>{{ reply.created_at }}</code></span>
                                </td>
                                <td style="width: 20%;">
                                    <form action="{% url 'delete_reply' reply.id %}" method="POST" style="display:inline;" onsubmit="return confirmDelete();">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-outline-danger btn-sm">删除回复</button>
                                    </form>
                                </td>
                                </tr>
                            {% empty %}

                            {% endfor %}
                        {% empty %}
                            <tr>没有评论可显示。</tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card shadow">
    <div class="card-footer bg-body-tertiary">
        <h1 class="text-center"><code>THAT'S THE END</code></h1>
    </div>
</div>

<script>
    function confirmDelete() {
        return confirm("确认删除这个帖子吗？");
    }
</script>

{% endblock %}

forum/templates/root.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-Hans">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>信安综合网站</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-5.3.3-dist/css/bootstrap.min.css' %}" />
    <style>
      .main-container {
        flex-direction: row;
        display: flex;
        justify-content: space-between;
        gap: 20px; 
        padding: 20px;
        flex-wrap: wrap;
      }

      /* 左侧竖栏样式 */
      .left-sidebar,
      .right-sidebar {
        width: 225px;
        background-color: #f4f4f4;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        height: 100;
        a {
          color: gray;
          text-decoration: none;
        }
        a:hover {
          color: rgb(9, 88, 235);
        }
      }

      /* 内容区域样式 */
      .content-area {
        flex: 1;
        padding: 15px;
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
      }

      @media (max-width: 768px) {
        .main-container {
          flex-direction: column;
        }
        .left-sidebar, .right-sidebar {
          width: 100%; 
        }
      }
    </style>
    {% block style %}
    {% endblock %}
  </head>

  <header class="sticky-top">
    <nav class="navbar navbar-expand-md sticky-top border-bottom bg-body">
      <div class="container-fluid">
        <h3 class="fw-bolder"><a class="navbar-brand" href="#">信安综合网站</a></h3>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link" aria-current="page" href="/forum/home">论坛主页</a></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">帖子列表</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/forum/PostList">查看帖子</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">发布帖子</a>
              <ul class="dropdown-menu">
                {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="/forum/NewPost">新建帖子</a></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'login' %}">登录后发布</a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <form class="d-flex" role="search">
                <div class="input-group">
                  <span class="input-group-text">按主题</span>
                  <select class="form-select" name="subject">
                      <option value="">Search</option>
                      {% for subject in subjects %}
                          <option value="{{ subject.name }}" {% if subject.name == selected_subject %}selected{% endif %}>
                              {{ subject.name }}
                          </option>
                      {% endfor %}
                  </select>
                  <button class="btn btn-outline-success" type="submit">搜索</button>
                </div>
              </form>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item d-flex mx-2"><a class="nav-link" href="/login/">登录</a></li>
            {% else %}
            <li class="nav-item d-flex mx-2 dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">{{ user.username|default_if_none:"用户" }}</a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="{% url 'user_page:user_page' %}">个人主页</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">注销</a></li>
              </ul>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <body>
    {% include "theme_toggler.html" %}

    <!-- 主体内容区域 -->
    <div class="main-container">
      <!-- 左侧竖栏 -->
      <div class="left-sidebar bg-body-tertiary">
        <h4>论坛公告</h4>
          <ul>
            <li><a href="#">2024年版论坛规则更新</a></li>
            <li><a href="#">系统维护公告：明天凌晨进行维护</a></li>
            <li><a href="#">关于近期网络安全漏洞的提醒，请尽快更新密码</a></li>
            <li><a href="#">注意：请勿随便点击不明链接以防受骗</a></li>
          </ul>

          <br>

          <h4>社区行为守则</h4>
          <ul> 
            <li><a href="#">请尊重他人，禁止恶意言论和行为</a></li>
            <li><a href="#">禁止发布违法、恶俗、不当内容</a></li>
            <li><a href="#">请勿滥用举发帖功能，保持论坛的良好氛围</a></li>
          </ul>


      </div>

      <!-- 内容区域 -->
      <div class="content-area bg-body-tertiary">
        {% block content %}
        {% endblock %}
      </div>

      <!-- 右侧竖栏 -->
      <div class="right-sidebar bg-body-tertiary"> 
        <h3><code>参与投票</code></h3>
        <form>
          <div>
            <label>你最喜欢哪种编程语言？</label>
            <select class="form-select" name="language">
              <option value="python">Python</option>
              <option value="c">C</option>
              <option value="c++">C++</option>
              <option value="c#">C#</option>
              <option value="go">Go</option>
              <option value="javascript">JavaScript</option>
              <option value="java">Java</option>
              <option value="php">PHP</option>
              <option value="ruby">Ruby</option>
              <option value="rust">Rust</option>
              <option value="swift">Swift</option>
              <option value="typescript">TypeScript</option>
              <option value="other">其他</option>
            </select>
          </div>
          <button type="submit" class="btn btn-secondary mt-2 mb-4">投票</button>
        </form>

        <br>

        <h4>平台更新日志</h4>
        <ul>
          <li><a href="#">v1.2.0版本更新：修复了部分bug，优化了页面加载速度</a></li>
          <li><a href="#">v1.1.0版本上线：美化了页面布局</a></li>
          <li><a href="#">v1.0.6版本更新：新增了收藏功能</a></li>
          <li><a href="#">v1.0.5版本更新：提高了搜索性能</a></li>
        </ul>

      </div>

    <script src="{% static 'plugins/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/color-modes.js' %}"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>